<a href="https://colab.research.google.com/github/Haebuk/sparta_ML/blob/main/3%EC%A3%BC%EC%B0%A8_%EC%8B%A4%EC%8A%B5_01_%EB%94%A5%EB%9F%AC%EB%8B%9D_XOR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam, SGD

# XOR 데이터셋

![](https://i.imgur.com/llFchxI.png)

In [2]:
x_data = np.array([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=np.float32) # 케라스 float32
y_data = np.array([[0], [1], [1], [0]], dtype=np.float32)

# XOR 이진 논리 회귀

In [3]:
model = Sequential([
  Dense(1, activation='sigmoid')
])

model.compile(loss='binary_crossentropy', optimizer=SGD(lr=0.1))

model.fit(x_data, y_data, epochs=1000, verbose=0)

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py:375: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  "The `lr` argument is deprecated, use `learning_rate` instead.")


In [4]:
y_pred = model.predict(x_data)

print(y_pred) # 0 1 1 0이 나와야 하는데 전부 .5가 나옴 - 이진 논리 회귀로 불가능

[[0.50027704]
 [0.499734  ]
 [0.500353  ]
 [0.4998099 ]]


# XOR 딥러닝(MLP)

In [5]:
model = Sequential([
  Dense(8, activation='relu'), # 히든 레이어 추가
  Dense(1, activation='sigmoid'),
])

model.compile(loss='binary_crossentropy', optimizer=SGD(lr=0.1))

model.fit(x_data, y_data, epochs=1000, verbose=0)

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py:375: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  "The `lr` argument is deprecated, use `learning_rate` instead.")


In [6]:
y_pred = model.predict(x_data)

print(y_pred) # 0 1 1 0 에 가까운 값

[[0.04378569]
 [0.9733304 ]
 [0.9853822 ]
 [0.01576218]]


# Keras Functional API

우리는 지금까지 Keras의 Sequential 클래스를 사용하여 Sequential API를 사용했습니다. Sequential API는 순차적인 모델 설계에는 편리한 API 이지만, 복잡한 네트워크를 설계하기에는 한계가 있기 때문에 실무에서는 Functional API를 주로 사용합니다.

위에서 했던 XOR 딥러닝 문제를 Functional API로 다시 작성해보겠습니다!

In [7]:
import numpy as np
from tensorflow.keras.models import Sequential, Model # Model 추가 임포트
from tensorflow.keras.layers import Dense, Input # Input 추가 임포트
from tensorflow.keras.optimizers import Adam, SGD

`model.summary()` 를 사용하여 모델의 구조를 확인할 수 있습니다.

Sequential API를 사용하면 구조를 확인하기 힘들지만 Functional API를 사용하면 `model.summary()`를 사용하여 구조를 확인하기 쉽다는 장점도 있습니다.

In [8]:
input = Input(shape=(2,)) # x1, x2
hidden = Dense(8, activation='relu')(input) # input을 넣어줌
output = Dense(1, activation='sigmoid')(hidden) # hidden을 넣어줌

model = Model(inputs=input, outputs=output) # Sequential 대신 Model

model.compile(loss='binary_crossentropy', optimizer=SGD(lr=0.1))

model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 2)]               0         
_________________________________________________________________
dense_3 (Dense)              (None, 8)                 24        
_________________________________________________________________
dense_4 (Dense)              (None, 1)                 9         
Total params: 33
Trainable params: 33
Non-trainable params: 0
_________________________________________________________________


/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py:375: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  "The `lr` argument is deprecated, use `learning_rate` instead.")


In [9]:
model.fit(x_data, y_data, epochs=1000, verbose=0)

y_pred = model.predict(x_data)

print(y_pred)

[[0.02274591]
 [0.98882955]
 [0.98360884]
 [0.01317763]]
